### ISSUE TITLE
Superuser guard

### ISSUE THREAD

**Issue by Bokoness** [Bokoness/kehilason#1]
Create superuser role in `users` table and validate that only super users can Create/Delete campaigns from server

1. modify `users` table to contain `is_superuser` col, bool, default to false
2. create middle ware for superuser validation
3. use this middle ware for Create/Delete endpoints on `campaigns` table

**Comment by aviel-lanzman** [comment]
Create superuser role in users table and validate that only super users can Create/Delete campaigns from server

1. [ ] modify `users` table to contain `is_superuser` col, bool, default to false
2. [ ] create middle ware for superuser validation
3. [ ] use this middle ware for Create/Delete endpoints on `campaigns` table

**Comment by Bokoness** [comment]
Yes

**Comment by Bokoness** [comment]
> @Bokoness 
> campaigns is communities?

Yep
